version: '3.8'

services:
  app:
    image: fatihgumush/bookstoreapi:latest
    container_name: app
    restart: always
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: test
      MYSQL_PASSWORD: TEST
    depends_on:
      - database
    networks:
      - bookstore_net
  
  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234.fdsa
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: test
      MYSQL_PASSWORD: TEST
    networks:
      - bookstore_net

networks:
  bookstore_net:
    driver: bridge