apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployment
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy # <- svc.label.selector ->
    spec:
      volumes:
        - name: nginx-conf # <- volume // volumeMount pair ->
          configMap:
            name: nginx-conf # <- volume // configMap pair ->
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: nginx-proxy
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-conf # <- volume // volumeMount pair ->
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
        - name: simple-webapp
          image: kodekloud/simple-webapp
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 500m