apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-deployment
  labels:
    app: nginx-proxy # <- deploy.template.label ->
spec:
  selector:
    app: nginx-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP